config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users,only: [:new, :create]
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  validates :status, presence: true, length: { maximum:10}
  validates :content, presence: true, length: { maximum:255}
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :email, presence: true, length: {maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private
  
  def login(email,password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  
  def index
    @tasks = current_user.tasks.order(id: :desc)
  end
  
  def show
  end
  
  def new
    @task = current_user.tasks.build # form_with 用
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      flash[:success] = 'Task が正常に作成されました'
      redirect_to @task
    else
      @tasks = current_user.tasks.order(id: :desc)
      flash.now[:danger] = 'Task が作成されませんでした'
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @task.update(task_params)
      flash[:success] = 'Task は正常に更新されました'
      redirect_to @task
    else
      flash.now[:danger]= ' Task は更新されませんでした'
      render :edit
    end
  end

  def destroy
    @task.destroy
    flash[:success]= 'Task は正常に削除されました'
    redirect_back(fallback_location: root_url)
  end
  
  private
  
  # Strong Parameter
  def task_params
    params.require(:task).permit(:content, :status)
  end
  
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザーを登録しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ユーザーの登録に失敗しました。'
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <% model.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<h1>tasklist</h1>
  <% if logged_in? %>
    <%= link_to 'Logout', logout_path, method: :delete %>
  <% else %>
    <%= link_to 'Signup',signup_path %>
    <%= link_to 'Login',login_path %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KadaiTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>  
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>

  <%= f.label :content, 'タスク' %>
  <%= f.text_field :content %>
  
  <%= f.label :status, 'ステータス' %>
  <%= f.text_field :status %>
  
  <%= f.submit '作成' %>
<% end %>

app/views/tasks/edit.html.erb
<h1>id: <%= @task.id%>のタスク編集ページ</h1>

<%= render 'form', task: @task %>

<%= link_to '一覧に戻る', tasks_path %>

app/views/tasks/index.html.erb
<h2>タスク一覧</h2>

  <ul>
    <% @tasks.each do |task| %>
    <li><%= link_to task.id, task %> : <%= task.content %> &gt; <%= task.status %></li>
    <% end %>
  </ul>

  <%= link_to '新規タスクの追加', new_task_path %>

app/views/tasks/new.html.erb
<h1>タスク新規作成ページ</h1>

<%= render 'form', task: @task %>

<%= link_to '一覧に戻る', tasks_path %>

app/views/tasks/show.html.erb
<h1>タスク詳細ページ</h1>

<p><%= @task.content %></p>
<p><%= @task.status %></p>

<%= link_to '一覧に戻る', tasks_path %>
<%= link_to 'このタスクを編集する', edit_task_path(@task) %>
<%= link_to 'このタスクを削除する', @task, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }  %>

app/views/users/new.html.erb
<h2>Sign up</h2>

<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  
  <%= f.label :email %>
  <%= f.email_field :email %>
    
  <%= f.label :password %>
  <%= f.password_field :password %>
    
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
    
  <%= f.submit 'Sign up' %>
<% end %>